# Generated by Django 3.2.18 on 2023-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
