# Generated by Django 3.2.18 on 2023-05-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_reservationmodel_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roommodel',
            unique_together={('name', 'capacity')},
        ),
    ]
