# Generated by Django 3.2.18 on 2023-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roommodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='most_resident_period',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='end_date',
            field=models.DateField(verbose_name='End of residence date'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of residents'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='start_date',
            field=models.DateField(verbose_name='Start of residence date'),
        ),
    ]
