# Generated by Django 3.2.18 on 2023-05-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20230502_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='most_resident_period',
        ),
    ]
