# Generated by Django 3.2.18 on 2023-05-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_roommodel_most_resident_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='quantity',
        ),
    ]
