# Generated by Django 3.2.18 on 2023-05-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_roommodel_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationModel',
        ),
    ]
