# Generated by Django 3.2.18 on 2023-05-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0007_delete_reservationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start of residence date')),
                ('end_date', models.DateField(verbose_name='End of residence date')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Number of residents')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='rooms.roommodel')),
            ],
        ),
    ]
